<a href="https://colab.research.google.com/github/heejjj/Health_Bio_AI/blob/bio_colab/030723_python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import numpy as np

- 벡터화 : 배열은 for문을 작성하지 않고, 데이터를 일괄 처리 하는 것.
    - 같은 크기의 배열 간의 산술 연산은 배열의 각  원소 단위로 적용됨.




- 브로드 캐스팅 
  - 다른 모양의 벼열 간의 산술 연산을 수행 할 수 있도록 해주는 numpy의 기능
  - 연산을 수행하는 축을 제외한 나머지 축의 shape이 일치하거나 둘 중 하나의 길이기ㅏ 1이여야함. 
  - 다른 배열들 간의 연산이 어떤 조건을 만족했을 때 가능해지도록 배열을 자동적으로 변환하는 것. 

In [7]:
A = np.array([1,2,3,4],int)
print(type(A))
print(A)

<class 'numpy.ndarray'>
[1 2 3 4]


In [8]:

A = np.array([1,2,3,4],str)
print(type(A))
print(A)

<class 'numpy.ndarray'>
['1' '2' '3' '4']


In [9]:
import numpy as np
A = np.array([1,2,3,4],float)
print(type(A))
print(A)

<class 'numpy.ndarray'>
[1. 2. 3. 4.]


In [10]:
A = [1,2,3,4]

a = np.array(A)
s = A[:2]

print('A의 출력입니다. %a' %a)
print('s의 출력입니다. %s' %s)

A의 출력입니다. array([1, 2, 3, 4])
s의 출력입니다. [1, 2]


In [11]:
ss = a[:2].copy()
print(ss.size)
ss[0]=99
print(a)
print(s)
print(ss)

2
[1 2 3 4]
[1, 2]
[99  2]


In [4]:
arr = np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
arr+arr

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [6]:
10 -arr

array([[9, 8, 7],
       [6, 5, 4]])