<a href="https://colab.research.google.com/github/heejjj/Health_Bio_AI/blob/bio_colab/tensor_practice_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Tensor

Tensor는 multi-dimensional array를 나타내는 말로, TensorFlow의 기본 data type입니다

In [ ]:
import numpy as np
import tensorflow as tf
# Hello World
hello = tf.constant([3,3], dtype=tf.float32)
print(hello)

tf.Tensor([3. 3.], shape=(2,), dtype=float32)


In [ ]:
# 상수형 tensor는 아래와 같이 만들 수 있습니다
# 출력해보면 tensor의 값과 함께, shape과 내부의 data type을 함께 볼 수 있습니다
x = tf.constant([[1.0, 2.0],
                 [3.0, 4.0]])

#x= tensor 
print(x)
print(type(x))

tf.Tensor(
[[1. 2.]
 [3. 4.]], shape=(2, 2), dtype=float32)
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [ ]:
# 아래와 같이 numpy ndarray나 python의 list도 tensor로 바꿀 수 있습니다
x_np = np.array([[1.0, 2.0],
                [3.0, 4.0]])
x_list = [[1.0, 2.0], 
         [3.0, 4.0]]

print(type(x_np))
print(type(x_list))

<class 'numpy.ndarray'>
<class 'list'>


In [ ]:
#array와 

x_np = tf.convert_to_tensor(x_np)
x_list = tf.convert_to_tensor(x_list)

print(type(x_np))
print(type(x_list))

<class 'tensorflow.python.framework.ops.EagerTensor'>
<class 'tensorflow.python.framework.ops.EagerTensor'>


In [ ]:
# 반대로 tensor를 다음과 같이 numpy ndarray로 바꿀 수도 있습니다
x.numpy()

array([[1., 2.],
       [3., 4.]], dtype=float32)

In [ ]:
print(type(x.numpy()))

<class 'numpy.ndarray'>


In [ ]:
a = tf.ones((2,3)) #2x3 matrix 
b = tf.zeros((2,3))
c = tf.fill((2,2), 2)
print(a)
print(b)
print(c)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[0. 0. 0.]
 [0. 0. 0.]], shape=(2, 3), dtype=float32)
tf.Tensor(
[[2 2]
 [2 2]], shape=(2, 2), dtype=int32)


In [ ]:
d = tf.zeros_like(c)
e = tf.ones_like(c)
print(d)
print(e)

tf.Tensor(
[[0 0]
 [0 0]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[1 1]
 [1 1]], shape=(2, 2), dtype=int32)


In [ ]:
f = tf.eye(3)
print(f)


#eye = Imaxtircs

tf.Tensor(
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]], shape=(3, 3), dtype=float32)


In [ ]:
g  = tf.range(10)
print(g)

#range(n) : 0~ n-1 
#range(a,b) : a~ b-1


tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int32)


In [ ]:
h = tf.random.uniform((2,2)) # np.rand
i = tf.random.normal((2,2))  # np.randn
print(h)
print(i)

#random -> 임의의 난수
#1. uniform 0~1사이의 수
#2. normal (표준정규분포; 중간값: 평균0, deviation ): -무한대~ +무한대까지 가능하나 
#대부분 0에 가까운 값의 확률이 높음 

tf.Tensor(
[[0.95396125 0.04452229]
 [0.13352883 0.65095925]], shape=(2, 2), dtype=float32)
tf.Tensor(
[[-0.84587514  0.09610429]
 [-1.4401312  -0.1287323 ]], shape=(2, 2), dtype=float32)


#### Tensor의 속성

In [ ]:
tensor = tf.random.normal((3,4))

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")

Shape of tensor: (3, 4)
Datatype of tensor: <dtype: 'float32'>


In [ ]:
# 속성 변경
tensor = tf.reshape(tensor, (4, 3))
tensor = tf.cast(tensor, tf.int32)
#cast 데이터 타입이 바뀜

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")

### Variable

Variable은 변할 수 있는 상태를 저장하는데 사용되는 특별한 텐서입니다.
딥러닝에서는 학습해야하는 가중치(weight, bias)들을 variable로 생성합니다.

In [ ]:
# tensor의 값 변경 - 변경 불가능
tensor = tf.ones((3,4))
print(tensor)

tensor[0,0] = 2.

In [ ]:
# variable 만들기, 값 변경
variable = tf.Variable(tensor)
print(variable)

variable[0,0].assign(2)
print(variable)

In [ ]:
#딥러닝 초기값에서 -> 값을 업데이트 하며 진행됨
# 초기값을 사용해서 Variable을 생성할 수 있습니다
initial_value = tf.random.normal(shape=(2, 2))
#초기값이 0부터 시작하면, local minimum에 빠질 수 있어서, random한 weight값으로 시작
#초기 값이 달라서, 돌리는 사람마다 결과가 다름
#5-10번 해서 평균을 내는게 일반적
weight = tf.Variable(initial_value)
print(weight)


#딥러닝의 성능평가 -> 증명하기 어려움

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.9821699 ,  0.13059866],
       [ 1.0764698 ,  0.6528772 ]], dtype=float32)>


In [ ]:
# 아래와 같이 variable을 초기화해주는 initializer들을 사용할 수도 있습니다
#standard deviation값을 조절하여, 정규분포의 편차를 조절할 수 있음 
weight = tf.Variable(tf.random_normal_initializer(stddev=1.)(shape=(2,2)))
print(weight)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.11523245, -3.0945446 ],
       [ 0.66705936, -0.7939015 ]], dtype=float32)>


In [ ]:
# variable은 `.assign(value)`, `.assign_add(increment)`, 또는 `.assign_sub(decrement)`
# 와 같은 메소드를 사용해서 Variable의 값을 갱신합니다:'''


#wight가 tensor였을때, assign을 통해서, weight를 바꿀 수 있다.
new_value = tf.random.normal(shape=(2,2))
print(new_value)
weight.assign(new_value)
print(weight)

tf.Tensor(
[[-0.05195293  2.8822281 ]
 [-1.0142945   3.3181446 ]], shape=(2, 2), dtype=float32)
<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-0.05195293,  2.8822281 ],
       [-1.0142945 ,  3.3181446 ]], dtype=float32)>


In [ ]:
#tf값은 broad casting이 안됨.
#1로 채워진 matrix를 만들고 나서 통채로 빼면됨
#또는 tf.ones_like(weight)를 쓰면 됨
#sub -> subtraction(뺄셈)
added_value = tf.ones(shape=(2,2))
weight.assign_sub(added_value) #빼기 
#weight.assign_ad(added_value) 더하기


print(weight)

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[-1.051953 ,  1.8822281],
       [-2.0142946,  2.3181446]], dtype=float32)>


In [ ]:
### Tensor

#Tensor는 multi-dimensional array를 나타내는 말로, TensorFlow의 기본 data type입니다

# Hello World
hello = tf.constant([3,3], dtype=tf.float32)
print(hello)

# 상수형 tensor는 아래와 같이 만들 수 있습니다
# 출력해보면 tensor의 값과 함께, shape과 내부의 data type을 함께 볼 수 있습니다
x = tf.constant([[1.0, 2.0],
                 [3.0, 4.0]])
print(x)
print(type(x))

# 아래와 같이 numpy ndarray나 python의 list도 tensor로 바꿀 수 있습니다
x_np = np.array([[1.0, 2.0],
                [3.0, 4.0]])
x_list = [[1.0, 2.0], 
         [3.0, 4.0]]

print(type(x_np))
print(type(x_list))

x_np = tf.convert_to_tensor(x_np)
x_list = tf.convert_to_tensor(x_list)

print(type(x_np))
print(type(x_list))

# 반대로 tensor를 다음과 같이 numpy ndarray로 바꿀 수도 있습니다
x.numpy()

print(type(x.numpy()))

a = tf.ones((2,3))
b = tf.zeros((2,3))
c = tf.fill((2,2), 2)
print(a)
print(b)
print(c)

d = tf.zeros_like(c)
e = tf.ones_like(c)
print(d)
print(e)

f = tf.eye(3)
print(f)

g  = tf.range(10)
print(g)

h = tf.random.uniform((2,2)) # np.rand
i = tf.random.normal((2,2))  # np.randn
print(h)
print(i)

#### Tensor의 속성

tensor = tf.random.normal((3,4))

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")

# 속성 변경
tensor = tf.reshape(tensor, (4, 3))
tensor = tf.cast(tensor, tf.int32)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensor: {tensor.dtype}")

### Variable

"""Variable은 변할 수 있는 상태를 저장하는데 사용되는 특별한 텐서입니다.
딥러닝에서는 학습해야하는 가중치(weight, bias)들을 variable로 생성합니다."""

# tensor의 값 변경 - 변경 불가능
tensor = tf.ones((3,4))
print(tensor)

tensor[0,0] = 2.

# variable 만들기, 값 변경
variable = tf.Variable(tensor)
print(variable)

variable[0,0].assign(2)
print(variable)

# 초기값을 사용해서 Variable을 생성할 수 있습니다
initial_value = tf.random.normal(shape=(2, 2))
weight = tf.Variable(initial_value)
print(weight)

# 아래와 같이 variable을 초기화해주는 initializer들을 사용할 수도 있습니다
weight = tf.Variable(tf.random_normal_initializer(stddev=1.)(shape=(2,2)))
print(weight)

# variable은 `.assign(value)`, `.assign_add(increment)`, 또는 `.assign_sub(decrement)`
# 와 같은 메소드를 사용해서 Variable의 값을 갱신합니다:'''

new_value = tf.random.normal(shape=(2,2))
print(new_value)
weight.assign(new_value)
print(weight)

added_value = tf.ones(shape=(2,2))
weight.assign_sub(added_value)
print(weight)

### Indexing과 Slicing

In [ ]:
a = tf.range(1, 13)
a = tf.reshape(a, (3, 4))
print(a)

#ragne1~12까지 vector를 

tf.Tensor(
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]], shape=(3, 4), dtype=int32)


In [ ]:
# indexing
print(a[1])
print(a[0,-1])

tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)
tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
# slicing
print(a[1:-1])
print(a[:2, 2:])

### Transpose

In [ ]:
a = tf.range(16)
a = tf.reshape(a, (2, 2, -1))
print(a)

In [ ]:
b = tf.transpose(a, (2, 0, 1))
print(b)

### Tensor 연산

In [ ]:
x = tf.constant([[1,2], [3,4]], dtype=tf.float32)
y = tf.constant([[5,6], [7,8]], dtype=tf.float32)
print(x)
print(y)

In [ ]:
print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x @ y)
print('='*30)
print(tf.add(x, y))
print(tf.subtract(x, y))
print(tf.multiply(x, y))
print(tf.divide(x, y))
print(tf.matmul(x, y))

In [ ]:
z = tf.range(1, 11)
z = tf.reshape(z, (2, 5))
print(z)

In [ ]:
print(tf.reduce_sum(z))

In [ ]:
sum1 = tf.reduce_sum(z, axis=0)
sum2 = tf.reduce_sum(z, axis=1)
sum3 = tf.reduce_sum(z, axis=-1)
print(sum1)
print(sum2)
print(sum3)

In [ ]:
concat = tf.concat([z, z], axis=0)
print(concat)

In [ ]:
concat = tf.concat([z, z], axis=-1)
print(concat)

In [ ]:
stack = tf.stack([z, z], axis=0)
print(stack)

In [ ]:
stack = tf.stack([z, z], axis=-1)
print(stack)

In [ ]:
stack = tf.stack([z, z], axis=1)
print(stack)